### ISSUE TITLE
Some confusing problems when implementing Assignment 04.

### ISSUE THREAD

**Issue by mobsceneZ** [SVF-tools/SVF-Teaching#31]
Dear Sir,
    I am currently working on assignment 04, and previous implementations on Assignment 01-03 works all fine. However, when I
try to run assignment 04, it fails, the report shows: 
 running test1: 
[Pointer Analysis] Checking MAYALIAS
         FAILURE :MAYALIAS check <id:15, id:15> at ({ ln: 16  cl: 5  fl: Assignment-4/testcase/src/test1.c })
assign-4: /home/SVF-tools/SVF/lib/MemoryModel/PointerAnalysis.cpp:629: virtual void SVF::PointerAnalysis::validateSuccessTests(std::string): Assertion `false && "test case failed!"' failed.

when I debug it with gdb, it seems like the problem is on ander->analyze().
The backtrace is as below: 
![image](https://user-images.githubusercontent.com/33396195/141982506-b13208ee-f040-466f-9dfe-ad3bac969e1d.png)
I'm really confused since ander->analyze() works fine on assignment-3, any suggestions are really appreciated! Thanks!
Here is my e-mail address if discussing on github is not that desirable: zjuzlm01@gmail.com =)

**Comment by ApsarasX** [comment]
I also encountered this problem!

**Comment by ApsarasX** [comment]
Hey, bro. May I refer to the Assignment-4 you completed?

**Comment by yuleisui** [comment]
`ander->analyze` is calling into your Andersen's implementation (Assign-3). For testing purposes, you do need working Assignments 2 and 3 as `aliasCheck` will rely on the Andersen's results.

If there is still an error in `aliasCheck`, it means that your Andersen's implementation is wrong.

**Comment by mobsceneZ** [comment]
> Hey, bro. May I refer to the Assignment-4 you completed?

I released my own solutions on my own repository, you can check it out :)

**Comment by yuleisui** [comment]
Please do not make it public since this will be used for other students. You two can talk offline for your solutions. Thanks.

**Comment by mobsceneZ** [comment]
> `ander->analyze` is calling into your Andersen's implementation (Assign-3). For testing purposes, you do need working Assignments 2 and 3 as `aliasCheck` will rely on the Andersen's results.
> 
> If there is still an error in `aliasCheck`, it means that your Andersen's implementation is wrong.

Dear Sir, I guess the problem is not on aliasCheck(), since the stack trace stuckes on ander->analyze() in taintChecking() actually, which has not yet reached aliasCheck() function. :(

Instead, the problem seems to occur on function validateSuccessTests() in /home/SVF-tools/SVF/lib/MemoryModel/PointerAnalysis.cpp:629, here is a snapshot: 
<img width="687" alt="捕获" src="https://user-images.githubusercontent.com/33396195/145676263-00daff47-8c99-4fcd-9710-0811010b66da.PNG">

**Comment by mobsceneZ** [comment]
> Please do not make it public since this will be used for other students. You two can talk offline for your solutions. Thanks.

got it, I will make it private, sorry T T

**Comment by mobsceneZ** [comment]
> Hey, bro. May I refer to the Assignment-4 you completed?

Here is my email address, you can contact with me through it : zjuzlm01@gmail.com

**Comment by mbarbar** [comment]
Do either of you use `getCopyOutEdges` or `getCopyInEdges` in your Andersen's solution? If so, I suggest replacing this with one of the APIs in the wiki. :)

**Comment by czcq** [comment]
> 

yeah,I met the same problem ,and I use ```getDirectOutEdge()``` to replace ```getCopyOutEdges()```,everything is OK,Thanks!! : )

**Comment by mobsceneZ** [comment]
> Do either of you use `getCopyOutEdges` or `getCopyInEdges` in your Andersen's solution? If so, I suggest replacing this with one of the APIs in the wiki. :)

Great! Now that all test cases passed, thanks for ur suggestion!

**Comment by xuanzhiliu** [comment]
> > Do either of you use `getCopyOutEdges` or `getCopyInEdges` in your Andersen's solution? If so, I suggest replacing this with one of the APIs in the wiki. :)
> 
> Great! Now that all test cases passed, thanks for ur suggestion!

Hey bro. I faced the same problem and I changed the APIs but this problem still exists. Can you share your code with me? I promise you I will keep it as private. Thanks!
