### ISSUE TITLE
Strange error occurred after I updated the lasted SVF

### ISSUE THREAD

**Issue by chenyang2022morecode** [SVF-tools/SVF-Teaching#34]
![image](https://user-images.githubusercontent.com/16433413/148686273-291da0a0-894e-41cb-9b7a-9a810802b0da.png)

After I updated to the lasted version of [SVF](https://github.com/SVF-tools/SVF/commit/1e92bf498a78ff9bd823515237c3e5186c6b47ae)，the assignment that was written before does not work properly...

**Comment by czcq** [comment]
I found that assignment 2, 3, and 4 all fail when running test2, but if test1 is commented out, test2 will pass, so I guess the resources of test1 are not released correctly.

**Comment by czcq** [comment]
when I run test1() and test2() , test2() failed
![image](https://user-images.githubusercontent.com/16433413/148686878-90578e53-843b-41d3-8d73-bf89f2715a5b.png)

but when I commented test1(),test2() passed..
![image](https://user-images.githubusercontent.com/16433413/148686944-4549d9e9-2fae-484b-b7c0-7285081350b0.png)

I have tried to replace ` PAG::releasePAG();`  with `SVFIR::releasePAG();` , but no effect

**Comment by czcq** [comment]
when
```
test1();
test2();
```
break at test1() -> assert
![372aac29ed5ff5fe747c0fa91ab8544](https://user-images.githubusercontent.com/16433413/148687357-8b3f4433-e27d-48f9-9f5f-31da72ec8170.png)



when
```
test2();
test1(); // assert will fail
```
![f0d6ef962ecd53ec45992162b26edfe](https://user-images.githubusercontent.com/16433413/148687381-5242485e-f4eb-49ca-a294-195cdb198c1e.png)

symTable->getTotalSymNum() is not correct

**Comment by czcq** [comment]
I read the relevant source code and found that there may be bugs here.



```SVFModule *svfModule = LLVMModuleSet::getLLVModuleSet()->buildSVFModule(moduleNameVec);```The svfModule is not released, so ```NodeIDAllocator::unset();``` is not called either, the singleton object ```NodeIDAllocator``` has not been released. After my experiments, even if the ```delete svfModule``` is called additionally, since the ```unset``` function does not set ```allocator``` to ```nullptr``` after the ```delete```, the old allocator will be reused, which should be regarded as a UAF vulnerability
````
//NodeIDAllocator.cpp
   void NodeIDAllocator::unset(void)
     {
         if (allocator != nullptr)
         {
             delete allocator;
         }
     }
````

``` symInfo->totalSymNum = NodeIDAllocator::get()->endSymbolAllocation();```, since the allocator is not released, the field```numNodes``` will always be accumulated and will not be cleared .

**Comment by chenyang2022morecode** [comment]
#35 this is my pull request

**Comment by yuleisui** [comment]
[#601 in SVF](https://github.com/SVF-tools/SVF/pull/601)  has been merged.

https://github.com/SVF-tools/SVF/commit/e9da085c236cbca3aab0e2ed61ca56be5cc33b1a and https://github.com/SVF-tools/SVF-Teaching/commit/17f6e102ab68c84c25f86564c1ea1c5e6f273f4b should fix your problem.

Please update SVF and SVF-Teaching, and let me know if your problem still exists

**Comment by yuleisui** [comment]
https://github.com/SVF-tools/SVF/commit/786e2501d87173762d969fcaaaf0d9de36c9a1ca should solve the destructor issue in AndersenBase.

**Comment by chenyang2022morecode** [comment]
Everything is OK,thank you sir!
