### ISSUE TITLE
I have problem in CodeGraphs exercise.

### ISSUE THREAD

**Issue by lcy8047** [SVF-tools/SVF-Teaching#36]
Dear Sir,
I stuck in CodeGraphs exercise.
Segmentation fault occurs in line 55 in CodeGraph.cpp, so I find the location that segfault occurs.
How can I fix it?
Please give me any advice.

![image](https://user-images.githubusercontent.com/35690965/150980902-b8133696-7207-4472-98da-7d0a1932b247.png)

`line 55 in CodeGraph.cpp`

```cpp
...
SVFIRBuilder builder;
...
```

`getPAG() in line 55 in SVFIRBuilder.h`

```cpp
...
/// Constructor
SVFIRBuilder(): pag(SVFIR::getPAG()), svfMod(nullptr), curBB(nullptr),curVal(nullptr)
{
}
...
```

`line 110 in getPAG in SVFIR.h`

```cpp
/// Singleton design here to make sure we only have one instance during any analysis
//@{
static inline SVFIR* getPAG(bool buildFromFile = false)
{
    if (pag == nullptr)
    {
        pag = new SVFIR(buildFromFile); // line 110 is here !
    }
    return pag;
}
```

`call build function in line 45 in SVFIR Constructor in SVFIR.cpp`

```cpp
SVFIR::SVFIR(bool buildFromFile) : IRGraph(buildFromFile)
{
	icfg = new ICFG();
	ICFGBuilder builder(icfg);
	builder.build(getModule()); // line 45 is here !
}
```

- `getModule()` returns nullptr. So, parameter of `build()` is `nullptr`
    
    ```cpp
    // line 155~158 in SVFIR.h 
    inline SVFModule* getModule()
    {
    	return SymbolTableInfo::SymbolInfo()->getModule();
    }
    ```
    
    - `SymbolInfo()->getModule()`
        
        ```cpp
        // line 157 ~ 161 in SymbolTableinfo.h
        /// Module
        inline SVFModule* getModule()
        {
        	return mod;
        }
        ```
        
    - `SymbolTableInfo::SymbolInfo()`
        
        ```cpp
        *// line 59 ~ 67 in SymbolTableInfo.cpp*
        SymbolTableInfo SymbolTableInfo::SymbolInfo()
        {
        	if (symInfo == nullptr)
        	{
        		symInfo = new SymbolTableInfo();
        		symInfo->setModelConstants(Options::ModelConsts);
        	}
        	return symInfo;
        }
        ```
        
    - SymbolTableInfo Constructor
        - In line 116, `mod` initializes with `nullptr`
        
        ```cpp
        // line 114 ~ 118
        /// Constructor
        SymbolTableInfo(void) :
        mod(nullptr), modelConstants(false), totalSymNum(0), maxStruct(nullptr), maxStSize(0)
        {
        }
        ```
        
    - `setModelConstants()`
        - Any lines not set `mod` variable
        
        ```cpp
        void setModelConstants(bool _modelConstants)
        {
            modelConstants = _modelConstants;
        }
        ```
        
    
    → So, `getModule()` returns `nullptr`
    

- line 41 ~ 54 in `ICFGBuilder::build()` in ICFGBuilder.cpp
    - Segfault occur in line 43. Because `svfModule` is nullptr

```cpp
void ICFGBuilder::build(SVFModule* svfModule)
{
	for (SVFModule::const_iterator iter = svfModule->begin(), eiter = svfModule->end(); iter != eiter; ++iter)
	{
		const SVFFunction *fun = *iter;
		if (SVFUtil::isExtCall(fun))
			continue;
		WorkList worklist;
		processFunEntry(fun,worklist);
		processFunBody(worklist);
		processFunExit(fun);
	}
	connectGlobalToProgEntry(svfModule);
}
```
![image](https://user-images.githubusercontent.com/35690965/150981063-fee5c2d0-4c72-4cb9-93ee-d644d1c729be.png)

- Before calling `build()`, I checked rsi register is null.
    
    Segmentation fault occur in `mov 0x28(%rsi), %rsi` instruction
    
   ![image](https://user-images.githubusercontent.com/35690965/150981233-c526a543-bf0e-465d-bea5-be29de18b6ac.png)

**Comment by yuleisui** [comment]
This should fix your problem https://github.com/SVF-tools/SVF-Teaching/commit/86c987273c6e52e556874661c1a44b0d3b2d7e24

**Comment by lcy8047** [comment]
It works! Thank you, Sir!
